#ifndef _PINMODE
#define _PINMODE
    #include <Arduino.h>
    #include "pinout.h"
    void definir_pinout(){
        pinMode(lamp1, OUTPUT);
        pinMode(lamp2, OUTPUT);
        pinMode(lamp3, OUTPUT);
        pinMode(lamp4, OUTPUT);
        pinMode(lamp5, OUTPUT);
        pinMode(lamp6, OUTPUT);
        pinMode(lamp7, OUTPUT);
        pinMode(lamp8, OUTPUT);
        pinMode(lamp9, OUTPUT);
        pinMode(lamp10, OUTPUT);
        pinMode(lamp11, OUTPUT);
        pinMode(lamp12, OUTPUT);
        pinMode(lamp13, OUTPUT);
        pinMode(lamp14, OUTPUT);
        pinMode(lamp15, OUTPUT);
        pinMode(lamp16, OUTPUT);
        pinMode(lamp17, OUTPUT);
        pinMode(lamp18, OUTPUT);
        pinMode(lamp19, OUTPUT);
        pinMode(lamp20, OUTPUT);
        pinMode(lamp21, OUTPUT);
        pinMode(lamp22, OUTPUT);  
        pinMode(Col0, INPUT_PULLUP);  
        pinMode(Col1, INPUT_PULLUP);  
        pinMode(Col2, INPUT_PULLUP);  
        pinMode(Col3, INPUT_PULLUP);  
        pinMode(Col4, INPUT_PULLUP);  
        pinMode(Col5, INPUT_PULLUP);  
        pinMode(Col6, INPUT_PULLUP);  
        pinMode(Col7, INPUT_PULLUP);  
    }
#endif // MACRO